### ISSUE TITLE
Use native methods for bit access

### ISSUE THREAD

**Issue by SoniEx2** [jDataView/jDataView#70]
https://github.com/jDataView/jDataView/blob/master/src/jdataview.js#L574

_getBytes produces unnecessary garbage. Please use native methods when possible. (e.g. if bitLength <= 8 use getUint8, if bitLength <= 16 use getUint16, etc)

**Comment by RReverser** [comment]
Again - why? This will slow down things on most platforms and make code much more polluted.

**Comment by SoniEx2** [comment]
How will it slow down things on most platforms?

**Comment by RReverser** [comment]
I already said in another thread - native `get*` DataView methods are slower, so doesn't make sense to use them when you can just take a needed slice of bytes on original buffer (this doesn't even create a copy, just another view on same memory) and use fast bitwise operations.

**Comment by RReverser** [comment]
If you're willing to create issue that doesn't reveal some actual bug, but is request for performance improvement, please add corresponding benchmarks so that we both don't waste time discussing theoretical questions and/or explaining something. Just "use something" without any ground or proof behind is counter-productive, so I'm closing this and similar issues for now.
