### ISSUE TITLE
Bitfields doesn't work well in littleEndian mode

### ISSUE THREAD

**Issue by mheden** [jDataView/jDataView#73]
The following code works as expected:
```javascript
      var view = new jDataView([0x4f, 0x01, 0x18], littleEndian = false);
      console.log("value: " + view.getInt16());
      console.log("ch1: "+ view.getUnsigned(1))
      console.log("ch2: "+ view.getUnsigned(1))
      console.log("ch3: "+ view.getUnsigned(1))
      console.log("ch4: "+ view.getUnsigned(1))
      console.log("ch5: "+ view.getUnsigned(1))
      console.log("ch6: "+ view.getUnsigned(1))
      console.log("ch7: "+ view.getUnsigned(1))
      console.log("ch8: "+ view.getUnsigned(1))
```
However, when setting `littleEndian = true` the browser (Firefox and Chrome) gives an out of bounds exception:
```
Uncaught RangeError: Offsets are out of bounds.
    e._checkBounds @ jdataview.js:263
    e._getBytes @ jdataview.js:317
    e._getBitRangeData @ jdataview.js:574
    e.getUnsigned @ jdataview.js:599
    (anonymous function) @ (index):54
```

**Comment by griffinmilsap** [comment]
This is occurring because Javascript doesn't support named parameters.  The function spec of jDataView() is buffer, offset, length, littleendian). When you pass 'littleEndian = false' as the second parameter of your constructor, it's actually evaluating the statement 'littleendian = false', which evaluates to 0 (in addition to creating a variable called littleEndian, and setting the offset into the buffer as 0.  Things work as expected here because you set an offset of 0 and you're expecting to treat the data as Big Endian.  When you set littleEndian to true in your example, the statement 'littleEndian = true' actually evaluates to the value 1, which is then set as your offset into the buffer.  This is why you overflow the buffer at the end, you started with an offset of 1.

In reality, the bitfield API doesn't support little endian operations at all.  It ignores the endianess setting and treats the data as big endian.  I see this as a bigger bug report, so I've created a new issue for it. #76
