### ISSUE TITLE
Remove old fallbacks

### ISSUE THREAD

**Issue by RReverser** [jDataView/jDataView#89]
When this library was created, DataView was a new WebGL extension available only in some browsers, but nowadays it's universally supported in JS engines.

We should remove old polyfills and let jDataView just take care of helper functionality (seeking, new types, etc.).

If someone wants to take this, please let me know.

**Comment by zadeviggers** [comment]
I'm interested in working on this - I've got some stuff I need to do with writing data in a custom binary format (with non-standard number formats) and jDataView seems like the only library out there really, and I don't want to start from scratch.

However it might make sense to work on modernizing the modules/build system before starting work on a big migration like this - it's going to be a major version bump, so we should take the time to tidy up the library for use in modern development:
- ES modules
- Type definitions (either JSDoc or a .d.ts file)
- Potentially move from Grunt to something like Vite

**Comment by RReverser** [comment]
Not sure about Vite - I'd probably just got with Rollup for bundling + npm scripts for other commands (test, lint) for simplicity - but otherwise sounds good. Go for it if you want.

**Comment by zadeviggers** [comment]
Okay I've gotten started. I did go with Vite (it uses Rollup under the hood, but with less config).

- I've removed all the old polyfill stuff, and made `jDataView` extend `DataView`
- I've updated some of the old-style code to be more modern (`var` vs `let`, `arguments` vs `...args`, etc)
- I've moved the testing to use Vitest and split the tests into separate files.  
  - Currently the tests only run in Node, but I'm going to set up Vitest's browser testing system

- I set up CI with Github actions since I couldn't get your TravisCI going. I'm more than happy to change this back though
- I removed the `writeXXX` methods when I was clearing out all the old polyfill setters/getters. I can add them back, but I'm not sure how useful they are. Are they worth the extra API surface?

I'm currently stuck on some test fails with the setters and getters. I think I must have accidentally changed something I shouldn't have, since there are numbers that are just not matching up properly. I'd appreciate if you could take a look here, since I'm not too great at actually working with the binary operators in javascript.

**Comment by RReverser** [comment]
> I think I must have accidentally changed something I shouldn't have, since there are numbers that are just not matching up properly.

Haven't read through the code, but based on 

> * and made `jDataView` extend `DataView`

alone - are you still overriding all the `DataView` methods and passing correct value of `this._littleEndian` to base implemetation? If not, `DataView` will default to big-endian instead of whatever is configured.

I'd suggest still encapsulating `DataView` instead of inheriting it as encapsulation is less error-prone, especially if base class gets more methods in the future that we don't override yet.

**Comment by RReverser** [comment]
> * I removed the `writeXXX` methods when I was clearing out all the old polyfill setters/getters. I can add them back, but I'm not sure how useful they are. Are they worth the extra API surface?

I'd like to keep them, yes. Being able to omit offset and endianness arguments is basically main purpose of this library over native DataView, and, as the docs for the `writeXXX` methods say, it's pretty inconvenient to pass `undefined` to all the `setXXX` methods and that's why `writeXXX` exists instead.

It doesn't cost much to add them, either, especially when extending prototype dynamically like jDataView did before.

**Comment by zadeviggers** [comment]
Good points with the `writeXXX` methods.
I've also changed it to not extend `DataView` any more - it seemed easier at first, but yeah, it creates some hard issues.
